# Generated by Django 5.1.1 on 2024-10-07 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meme',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_generator_memes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meme',
            name='top_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme_generator.meme'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_generator_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
